__title__ = "flumine"
__description__ = "Betfair data record framework utilising betfair streaming"
__url__ = "https://github.com/liampauling/flumine"
__version__ = "0.9.0"
__author__ = "Liam Pauling"
__license__ = "MIT"
